#!/usr/bin/env python3
"""
Report Generator - Generates markdown reports from assessment data.
Creates a structured report directory similar to the existing assessment format.
"""

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


class ReportGenerator:
   """Generates assessment reports in markdown format."""

   def __init__(self, config: Dict):
      self.config = config
      self.output_dir = Path(config.get('output_dir', 'reports'))
      self.assessment_name = config.get('assessment', {}).get('name', 'Aestimare Assessment')
      self.organization = config.get('assessment', {}).get('organization', 'Organization')
      self.timestamp = datetime.now().strftime('%Y-%m-%d')

   def generate_all_reports(self, executive_summary: Dict, security: Dict,
                        infrastructure: Dict, cost: Dict, repos: List[Dict],
                        aws_data: Dict, github_data: Dict):
      """Generate all reports from assessment data."""
      logger.info(f"Generating reports to: {self.output_dir}")

      # Create directory structure
      self._create_directory_structure()

      # Generate reports
      self.generate_executive_summary(executive_summary)
      self.generate_security_report(security)
      self.generate_security_issues(security)
      self.generate_infrastructure_report(infrastructure, aws_data)
      self.generate_cost_report(cost)
      self.generate_repository_reports(repos)
      self.generate_appendices(aws_data, github_data)

      logger.info("Report generation complete")

   def _create_directory_structure(self):
      """Create the report directory structure."""
      dirs = [
         'Security/Issues',
         'Infrastructure/EC2',
         'Infrastructure/RDS',
         'Infrastructure/Lambda',
         'Infrastructure/S3',
         'Code-Repositories/Repos',
         'Code-Repositories/Product-Lines',
         'Cost-Analysis',
         'Product-Lines',
         'Appendices',
      ]

      for dir_path in dirs:
         (self.output_dir / dir_path).mkdir(parents=True, exist_ok=True)

   def generate_executive_summary(self, summary: Dict):
      """Generate the executive summary report."""
      md = f"""# {self.assessment_name}

**Organization:** {self.organization}
**Assessment Date:** {self.timestamp}
**Generated By:** Aestimare

---

## Executive Summary

{summary.get('narrative', 'Assessment summary not available.')}

---

## Overall Scores

| Category | Score | Rating |
|----------|-------|--------|
| **Overall** | {summary.get('overall_score', 'N/A')}/100 | {summary.get('overall_rating', 'N/A')} |
| **Infrastructure** | {summary.get('infrastructure_score', 'N/A')}/100 | |
| **Security** | {summary.get('security_score', 'N/A')}/100 | |
| **Code Quality** | {summary.get('code_score', 'N/A')}/100 | |

---

## Risk Summary

| Severity | Count |
|----------|-------|
| Critical | {summary.get('risks', {}).get('critical', 0)} |
| High | {summary.get('risks', {}).get('high', 0)} |
| Medium | {summary.get('risks', {}).get('medium', 0)} |
| Low | {summary.get('risks', {}).get('low', 0)} |

---

## Key Findings

"""

      for finding in summary.get('key_findings', []):
         md += f"- {finding}\n"

      md += """
---

## Critical Issues Requiring Immediate Attention

"""

      for issue in summary.get('critical_issues', []):
         md += f"1. **{issue}**\n"

      md += """
---

## Strengths

"""

      for strength in summary.get('strengths', []):
         md += f"- {strength}\n"

      md += """
---

## Cost Summary

"""

      cost_summary = summary.get('cost_summary', {})
      md += f"""| Metric | Value |
|--------|-------|
| Monthly Cost | ${cost_summary.get('monthly_cost', 0):,.2f} |
| Potential Savings | ${cost_summary.get('potential_savings', 0):,.2f}/month |
| Optimization Score | {cost_summary.get('optimization_score', 'N/A')}/100 |

---

## Recommendations

### Immediate (24-48 hours)

"""

      for rec in summary.get('recommendations', {}).get('immediate', []):
         md += f"1. {rec}\n"

      md += """
### Week 1

"""

      for rec in summary.get('recommendations', {}).get('week_1', []):
         md += f"1. {rec}\n"

      md += """
### Month 1

"""

      for rec in summary.get('recommendations', {}).get('month_1', []):
         md += f"1. {rec}\n"

      md += """
### Quarter 1

"""

      for rec in summary.get('recommendations', {}).get('quarter_1', []):
         md += f"1. {rec}\n"

      md += """
---

## Related Documents

- [[Security/Security-Assessment|Security Assessment]]
- [[Infrastructure/Overview|Infrastructure Overview]]
- [[Cost-Analysis/Overview|Cost Analysis]]
- [[Code-Repositories/Overall-Assessment|Code Repository Assessment]]
"""

      self._write_file('Executive-Summary.md', md)

   def generate_security_report(self, security: Dict):
      """Generate the security assessment report."""
      summary = security.get('summary', {})

      md = f"""# Security Assessment

**Assessment Date:** {self.timestamp}
**Overall Security Score:** {summary.get('overall_score', 'N/A')}/100
**Risk Level:** {summary.get('risk_level', 'N/A')}

---

## Summary

| Severity | Count |
|----------|-------|
| Critical | {summary.get('critical', 0)} |
| High | {summary.get('high', 0)} |
| Medium | {summary.get('medium', 0)} |
| Low | {summary.get('low', 0)} |
| **Total** | **{summary.get('total_issues', 0)}** |

---

## Security Issues

"""

      # Group issues by severity
      issues = security.get('issues', [])
      for severity in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']:
         severity_issues = [i for i in issues if i.get('severity') == severity]
         if severity_issues:
            md += f"### {severity} ({len(severity_issues)})\n\n"
            for issue in severity_issues:
               md += f"- **[{issue.get('id')}]** [[Security/Issues/{issue.get('id')}|{issue.get('title')}]]\n"
            md += "\n"

      md += """
---

## Positive Findings

"""

      for finding in security.get('positive_findings', []):
         md += f"- {finding}\n"

      md += """
---

## Recommendations

### Immediate Actions

"""

      for rec in security.get('recommendations', {}).get('immediate', []):
         md += f"1. {rec}\n"

      md += """
### Short-term (1 week)

"""

      for rec in security.get('recommendations', {}).get('short_term', []):
         md += f"1. {rec}\n"

      md += """
### Long-term

"""

      for rec in security.get('recommendations', {}).get('long_term', []):
         md += f"1. {rec}\n"

      md += """
---

## Related Documents

- [[Executive-Summary|Executive Summary]]
- [[Infrastructure/VPC-Network|Network Security]]
- [[Infrastructure/IAM|IAM Configuration]]
"""

      self._write_file('Security/Security-Assessment.md', md)

   def generate_security_issues(self, security: Dict):
      """Generate individual security issue files."""
      issues = security.get('issues', [])

      for issue in issues:
         issue_id = issue.get('id', 'SEC-000')
         title = issue.get('title', 'Unknown Issue')

         md = f"""# {issue_id}: {title}

**Severity:** {issue.get('severity', 'N/A')}
**Category:** {issue.get('category', 'N/A')}
**Resource Type:** {issue.get('resource_type', 'N/A')}

---

## Description

{issue.get('description', 'No description available.')}

---

## Risk

{issue.get('risk', 'Risk not assessed.')}

---

## Affected Resources

"""

         for resource in issue.get('affected_resources', []):
            md += f"- `{resource}`\n"

         md += f"""
---

## Evidence

{issue.get('evidence', 'No evidence provided.')}

---

## Remediation

{issue.get('remediation', 'No remediation guidance provided.')}

---

## References

"""

         for ref in issue.get('references', []):
            md += f"- {ref}\n"

         md += """
---

## Related Documents

- [[../Security-Assessment|Security Assessment]]
"""

         self._write_file(f'Security/Issues/{issue_id}.md', md)

   def generate_infrastructure_report(self, infrastructure: Dict, aws_data: Dict):
      """Generate infrastructure overview report."""
      summary = infrastructure.get('summary', {})
      inventory = infrastructure.get('inventory', {})

      md = f"""# Infrastructure Overview

**Assessment Date:** {self.timestamp}

---

## Summary Scores

| Category | Score |
|----------|-------|
| Architecture | {summary.get('architecture_score', 'N/A')}/100 |
| Reliability | {summary.get('reliability_score', 'N/A')}/100 |
| Performance | {summary.get('performance_score', 'N/A')}/100 |
| Operational Excellence | {summary.get('operational_score', 'N/A')}/100 |
| **Overall** | **{summary.get('overall_score', 'N/A')}/100** |

---

## Resource Inventory

### Compute

| Resource | Count |
|----------|-------|
| EC2 Instances | {inventory.get('ec2_instances', {}).get('total', 0)} |
| - Running | {inventory.get('ec2_instances', {}).get('running', 0)} |
| - Stopped | {inventory.get('ec2_instances', {}).get('stopped', 0)} |
| Lambda Functions | {inventory.get('lambda_functions', {}).get('total', 0)} |

### Database

| Resource | Count |
|----------|-------|
| RDS Instances | {inventory.get('rds_instances', {}).get('total', 0)} |
| DynamoDB Tables | {inventory.get('dynamodb_tables', 0) if isinstance(inventory.get('dynamodb_tables'), int) else inventory.get('dynamodb_tables', {}).get('total', 0)} |

### Networking

| Resource | Count |
|----------|-------|
| VPCs | {inventory.get('vpcs', 0)} |
| Subnets | {inventory.get('subnets', 0)} |
| S3 Buckets | {inventory.get('s3_buckets', 0)} |

---

## Architecture Review

### Strengths

"""

      for strength in infrastructure.get('architecture_review', {}).get('strengths', []):
         md += f"- {strength}\n"

      md += """
### Weaknesses

"""

      for weakness in infrastructure.get('architecture_review', {}).get('weaknesses', []):
         md += f"- {weakness}\n"

      md += """
### Modernization Opportunities

"""

      for opp in infrastructure.get('architecture_review', {}).get('modernization_opportunities', []):
         md += f"- {opp}\n"

      md += """
---

## Infrastructure Findings

"""

      findings = infrastructure.get('findings', [])
      for severity in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']:
         severity_findings = [f for f in findings if f.get('severity') == severity]
         if severity_findings:
            md += f"### {severity}\n\n"
            for finding in severity_findings:
               md += f"- **{finding.get('id')}**: {finding.get('title')}\n"
               md += f"  - Category: {finding.get('category')}\n"
               md += f"  - Recommendation: {finding.get('recommendation')}\n\n"

      md += """
---

## Deprecated Resources

"""

      for dep in infrastructure.get('deprecated_resources', []):
         md += f"- **{dep.get('resource')}**: {dep.get('issue')}\n"
         md += f"  - Migration: {dep.get('migration_path')}\n"

      md += """
---

## Related Documents

- [[Executive-Summary|Executive Summary]]
- [[EC2/Overview|EC2 Instances]]
- [[RDS/Overview|RDS Databases]]
- [[Lambda/Overview|Lambda Functions]]
- [[VPC-Network|VPC Networking]]
"""

      self._write_file('Infrastructure/Overview.md', md)

   def generate_cost_report(self, cost: Dict):
      """Generate cost analysis report."""
      summary = cost.get('summary', {})

      md = f"""# Cost Analysis

**Assessment Date:** {self.timestamp}

---

## Summary

| Metric | Value |
|--------|-------|
| Monthly Cost | ${summary.get('monthly_cost', 0):,.2f} |
| Projected Annual Cost | ${summary.get('projected_annual_cost', 0):,.2f} |
| Potential Monthly Savings | ${summary.get('potential_monthly_savings', 0):,.2f} |
| Potential Annual Savings | ${summary.get('potential_annual_savings', 0):,.2f} |
| Savings Percentage | {summary.get('savings_percentage', 0):.1f}% |
| Cost Efficiency Score | {summary.get('cost_efficiency_score', 'N/A')}/100 |

---

## Cost Breakdown by Service

| Service | Monthly Cost | % of Total |
|---------|-------------|------------|
"""

      for service, data in cost.get('cost_breakdown', {}).get('by_service', {}).items():
         if isinstance(data, dict):
            md += f"| {service} | ${data.get('cost', 0):,.2f} | {data.get('percentage', 0):.1f}% |\n"

      md += """
---

## Savings Opportunities

"""

      for opp in cost.get('savings_opportunities', []):
         md += f"""### {opp.get('id')}: {opp.get('title')}

- **Category:** {opp.get('category')}
- **Priority:** {opp.get('priority')}
- **Estimated Monthly Savings:** ${opp.get('estimated_monthly_savings', 0):,.2f}
- **Estimated Annual Savings:** ${opp.get('estimated_annual_savings', 0):,.2f}
- **Implementation Effort:** {opp.get('implementation_effort')}

**Current State:** {opp.get('current_state', 'N/A')}

**Recommended Action:** {opp.get('recommended_action', 'N/A')}

---

"""

      md += """
## Commitment Analysis

### Reserved Instances

"""

      ri = cost.get('commitment_analysis', {}).get('reserved_instances', {})
      md += f"""- Active: {ri.get('active', 0)}
- Expired: {ri.get('expired', 0)}
- Utilization: {ri.get('utilization', 'N/A')}%

"""

      md += """
### Savings Plans

"""

      sp = cost.get('commitment_analysis', {}).get('savings_plans', {})
      md += f"""- Active: {sp.get('active', 0)}
- Coverage: {sp.get('coverage', 'N/A')}%

---

## Unused Resources

"""

      for resource in cost.get('unused_resources', []):
         md += f"- **{resource.get('resource_type')}** `{resource.get('resource_id')}` - ${resource.get('monthly_cost', 0):,.2f}/month\n"
         md += f"  - Reason: {resource.get('reason')}\n"
         md += f"  - Recommendation: {resource.get('recommendation')}\n\n"

      md += """
---

## Right-Sizing Recommendations

"""

      for rec in cost.get('right_sizing', []):
         md += f"- **{rec.get('resource_type')}** `{rec.get('resource_id')}`\n"
         md += f"  - Current: {rec.get('current_size')} -> Recommended: {rec.get('recommended_size')}\n"
         md += f"  - Savings: ${rec.get('monthly_savings', 0):,.2f}/month\n\n"

      md += """
---

## Recommendations

### Quick Wins

"""

      for rec in cost.get('recommendations', {}).get('quick_wins', []):
         md += f"1. {rec}\n"

      md += """
### Short-term

"""

      for rec in cost.get('recommendations', {}).get('short_term', []):
         md += f"1. {rec}\n"

      md += """
### Long-term

"""

      for rec in cost.get('recommendations', {}).get('long_term', []):
         md += f"1. {rec}\n"

      md += """
---

## Related Documents

- [[Executive-Summary|Executive Summary]]
- [[Infrastructure/Overview|Infrastructure Overview]]
"""

      self._write_file('Cost-Analysis/Overview.md', md)

   def generate_repository_reports(self, repos: List[Dict]):
      """Generate code repository reports."""
      # Generate overall assessment
      self._generate_repo_overall(repos)

      # Generate individual repo reports
      for repo in repos:
         if 'error' not in repo:
            self._generate_repo_individual(repo)

   def _generate_repo_overall(self, repos: List[Dict]):
      """Generate overall repository assessment."""
      valid_repos = [r for r in repos if 'error' not in r and 'summary' in r]

      if not valid_repos:
         avg_score = 0
         total_loc = 0
      else:
         avg_score = sum(r['summary'].get('overall_score', 0) for r in valid_repos) / len(valid_repos)
         total_loc = sum(r.get('metrics', {}).get('lines_of_code', 0) for r in valid_repos)

      md = f"""# Code Repository Assessment

**Assessment Date:** {self.timestamp}
**Total Repositories:** {len(repos)}
**Average Score:** {avg_score:.1f}/100

---

## Summary

| Metric | Value |
|--------|-------|
| Total Repositories | {len(repos)} |
| Assessed Successfully | {len(valid_repos)} |
| Total Lines of Code | {total_loc:,} |
| Average Score | {avg_score:.1f}/100 |

---

## Repository Scores

| # | Repository | Overall | Completeness | Security | Best Practices | Coding Standards | Activity |
|---|------------|---------|--------------|----------|----------------|------------------|----------|
"""

      # Sort by score
      sorted_repos = sorted(valid_repos, key=lambda x: x.get('summary', {}).get('overall_score', 0), reverse=True)

      for i, repo in enumerate(sorted_repos, 1):
         summary = repo.get('summary', {})
         name = summary.get('repository_name', repo.get('name', 'Unknown'))
         md += f"| {i} | [[Repos/{name}\\|{name}]] | "
         md += f"{summary.get('overall_score', 'N/A')} | "
         md += f"{summary.get('completeness_score', 'N/A')} | "
         md += f"{summary.get('security_score', 'N/A')} | "
         md += f"{summary.get('best_practices_score', 'N/A')} | "
         md += f"{summary.get('coding_standards_score', 'N/A')} | "
         md += f"{summary.get('activity_level', 'N/A')} |\n"

      md += """
---

## Score Distribution

"""

      # Count by rating
      ratings = {}
      for repo in valid_repos:
         rating = repo.get('summary', {}).get('rating', 'Unknown')
         ratings[rating] = ratings.get(rating, 0) + 1

      for rating, count in sorted(ratings.items()):
         md += f"- **{rating}:** {count} repositories\n"

      md += """
---

## Related Documents

- [[Executive-Summary|Executive Summary]]
- [[Product-Lines/Overview|Product Lines]]
"""

      self._write_file('Code-Repositories/Overall-Assessment.md', md)

   def _generate_repo_individual(self, repo: Dict):
      """Generate individual repository report."""
      summary = repo.get('summary', {})
      metrics = repo.get('metrics', {})
      name = summary.get('repository_name', repo.get('name', 'Unknown'))

      md = f"""# Repository Assessment: {name}

**Assessment Date:** {self.timestamp}
**Overall Score:** {summary.get('overall_score', 'N/A')}/100
**Rating:** {summary.get('rating', 'N/A')}
**Activity Level:** {summary.get('activity_level', 'N/A')}

---

## Scores

| Category | Score |
|----------|-------|
| Overall | {summary.get('overall_score', 'N/A')}/100 |
| Completeness | {summary.get('completeness_score', 'N/A')}/100 |
| Security | {summary.get('security_score', 'N/A')}/100 |
| Best Practices | {summary.get('best_practices_score', 'N/A')}/100 |
| Coding Standards | {summary.get('coding_standards_score', 'N/A')}/100 |

---

## Metrics

| Metric | Value |
|--------|-------|
| Lines of Code | {metrics.get('lines_of_code', 0):,} |
| Files | {metrics.get('files_count', 0):,} |
| Primary Language | {metrics.get('primary_language', 'Unknown')} |
| Dependencies | {metrics.get('dependencies_count', 0)} |
| Contributors | {metrics.get('contributors_count', 0)} |
| Commits (30d) | {metrics.get('commits_30d', 0)} |

---

## Findings

"""

      for finding in repo.get('findings', []):
         severity = finding.get('severity', 'INFO')
         md += f"### [{severity}] {finding.get('title')}\n\n"
         md += f"**Category:** {finding.get('category')}\n\n"
         md += f"{finding.get('description')}\n\n"
         md += f"**Recommendation:** {finding.get('recommendation')}\n\n"
         md += "---\n\n"

      md += """
## Documentation

"""

      doc = repo.get('documentation_assessment', {})
      md += f"- README: {doc.get('readme_quality', 'N/A')}\n"
      md += f"- API Documentation: {'Yes' if doc.get('api_docs') else 'No'}\n"
      md += f"- Contributing Guide: {'Yes' if doc.get('contributing_guide') else 'No'}\n"
      md += f"- Changelog: {'Yes' if doc.get('changelog') else 'No'}\n"
      md += f"- License: {doc.get('license', 'Missing')}\n"

      md += """
## Testing

"""

      test = repo.get('testing_assessment', {})
      md += f"- Has Tests: {'Yes' if test.get('has_tests') else 'No'}\n"
      md += f"- Test Files: {test.get('test_files_count', 0)}\n"
      md += f"- CI/CD: {', '.join(test.get('ci_cd_systems', [])) or 'None'}\n"

      md += """
## Security

"""

      sec = repo.get('security_assessment', {})
      md += f"- .gitignore: {'Yes' if sec.get('gitignore_present') else 'No'}\n"
      md += f"- .env.example: {'Yes' if sec.get('env_example_present') else 'No'}\n"
      md += f"- Dependency Lock: {'Yes' if sec.get('dependency_lock_present') else 'No'}\n"
      md += f"- Security Policy: {'Yes' if sec.get('security_policy_present') else 'No'}\n"
      md += f"- Dependabot: {'Enabled' if sec.get('dependabot_enabled') else 'Not Enabled'}\n"
      md += f"- Branch Protection: {'Yes' if sec.get('branch_protection') else 'No'}\n"

      md += """
---

## Recommendations

"""

      for rec in repo.get('recommendations', {}).get('immediate', []):
         md += f"1. **[Immediate]** {rec}\n"

      for rec in repo.get('recommendations', {}).get('short_term', []):
         md += f"2. **[Short-term]** {rec}\n"

      for rec in repo.get('recommendations', {}).get('long_term', []):
         md += f"3. **[Long-term]** {rec}\n"

      self._write_file(f'Code-Repositories/Repos/{name}.md', md)

   def generate_appendices(self, aws_data: Dict, github_data: Dict):
      """Generate appendix documents."""
      # Data reference
      md = f"""# Data Reference

**Assessment Date:** {self.timestamp}

This document references the raw data files collected during the assessment.

---

## AWS Data

"""

      for account_name in aws_data.keys():
         md += f"### {account_name}\n\n"
         md += f"- Full data: `.data/aws/{account_name.lower().replace(' ', '_')}/full_data.json`\n"
         md += f"- Regional data: `.data/aws/{account_name.lower().replace(' ', '_')}/[region]/`\n"
         md += f"- Global services: `.data/aws/{account_name.lower().replace(' ', '_')}/global/`\n\n"

      md += """
## GitHub Data

"""

      for org_name in github_data.keys():
         md += f"### {org_name}\n\n"
         md += f"- Full data: `.data/github/{org_name.lower()}/full_data.json`\n"
         md += f"- Repository list: `.data/github/{org_name.lower()}/repo_list.json`\n\n"

      md += """
---

## Report Generation

This report was generated using Aestimare.
"""

      self._write_file('Appendices/Data-Reference.md', md)

   def _write_file(self, relative_path: str, content: str):
      """Write content to a file."""
      file_path = self.output_dir / relative_path
      file_path.parent.mkdir(parents=True, exist_ok=True)

      with open(file_path, 'w') as f:
         f.write(content)

      logger.debug(f"  Written: {relative_path}")


def main():
   """Test the report generator."""
   import yaml

   config_path = Path(__file__).parent.parent / 'config' / 'accounts.yaml'
   if not config_path.exists():
      config_path = Path(__file__).parent.parent / 'config' / 'accounts.example.yaml'

   with open(config_path, 'r') as f:
      config = yaml.safe_load(f)

   generator = ReportGenerator(config)
   print("Report Generator initialized successfully")
   print(f"Output directory: {generator.output_dir}")


if __name__ == '__main__':
   main()
